// <auto-generated />
namespace Ecommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_product_detail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_product_detail));
        
        string IMigrationMetadata.Id
        {
            get { return "201702091836546_remove_product_detail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
